---
title: "컴파일러 오류 CS0156"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
f1_keywords: CS0156
helpviewer_keywords: CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: "9"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 1a24aa212e8f8c1c8e03cdbe583f4c3f5a2e7de1
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="aa292-102">컴파일러 오류 CS0156</span><span class="sxs-lookup"><span data-stu-id="aa292-102">Compiler Error CS0156</span></span>
<span data-ttu-id="aa292-103">바로 바깥쪽 catch 절에 중첩된 finally 절에는 인수가 없는 throw 문을 사용할 수 없습니다.</span><span class="sxs-lookup"><span data-stu-id="aa292-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="aa292-104">매개 변수가 없는 [throw](../../csharp/language-reference/keywords/throw.md) 문은 매개 변수를 사용하지 않는 **catch** 절에서만 나타날 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="aa292-104">A [throw](../../csharp/language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="aa292-105">자세한 내용은 참조 [예외 처리문](../../csharp/language-reference/keywords/exception-handling-statements.md) 및 [예외 및 예외 처리](../../csharp/programming-guide/exceptions/index.md)합니다.</span><span class="sxs-lookup"><span data-stu-id="aa292-105">For more information, see [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md) and [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="aa292-106">다음 샘플에서는 CS0156을 생성합니다.</span><span class="sxs-lookup"><span data-stu-id="aa292-106">The following sample generates CS0156:</span></span>  
  
```  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
