---
title: "'Throw' 문은 'Catch' 문 외부 또는 'Finally' 문 내부에서 피연산자를 생략할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17185ec328cecc29560b28e878682005e2a8a9e8
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53768118"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>'Throw' 문은 'Catch' 문 외부 또는 'Finally' 문 내부에서 피연산자를 생략할 수 없습니다.
`Throw` 문 외부의 `Catch` 문에서 예외 개체의 이름을 제공해야 합니다.  
  
 **오류 ID:** BC30666  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  `System.Exception`에서 파생된 예외 개체의 이름을 지정합니다.  
  
2.  `Throw` 문이 `Catch` 블록 내부에 있도록 코드를 재구성합니다.  
  
## <a name="see-also"></a>참고 항목  
 [Throw 문](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Visual Basic의 예외 클래스](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Visual Basic에서 예외 및 오류 처리](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
